// Given two strings s and t which consist of only lowercase letters.
//
//        String t is generated by random shuffling string s and then add one more letter at a random position.
//
//        Find the letter that was added in t.
//
//        Example:
//
//        Input:
//        s = "abcd"
//        t = "edcba"
//
//        Output:
//        e
//
//        Explanation:
//        'e' is the letter that was added.


public class FindTheDifference389 {
    public char solution(String s, String t) {
        int num1 = 0;
        int num2 = 0;

        for (int i = 0; i < s.length(); i++) {
            num1 += (int)s.charAt(i);
            num2 += (int)t.charAt(i);
        }
        num2 += (int)t.charAt(t.length() - 1);

        return (char)(num2 - num1);
    }

    public char solution2(String s, String t) {
        char answer = 0;
        for (int i = 0; i < s.length(); i++) {
            answer ^= s.charAt(i);
            answer ^= t.charAt(i);
        }

        answer ^= t.charAt(t.length() - 1);
        return answer;
    }

    public static void main(String[] args) {
        char c = new FindTheDifference389().solution("abcd", "sbcda");
        System.out.println(c);
    }
}
